### ISSUE TITLE
Error: CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:123 (file):   file RENAME failed to rename

### ISSUE THREAD

**Issue by yaseenmd** [libimobiledevice-win32/libimobiledevice-vs#5]
I am getting below error while running this command: vcpkg\vcpkg install libiconv:x64-windows zlib:x64-windows openssl:x64-windows dirent:x64-windows getopt:x64-windows curl:x64-windows libzip:x64-windows

Error:
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:123 (file):
  file RENAME failed to rename

    C:/Users/myaseen/Documents/was/libimobiledevice-windows/vcpkg/buildtrees/libzip/src/TEMP/libzip-rel-1-5-2

  to

    C:/Users/myaseen/Documents/was/libimobiledevice-windows/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8

  because: No error

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
  ports/libzip/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)

Error: Building package libzip:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libzip:x64-windows
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by qmfrederik** [comment]
This really looks like a VCPKG issue, plus it works in the CI builds (see https://dev.azure.com/libimobiledevice-win32/imobiledevice-net/_build/results?buildId=587) and for me locally.

Things you can try:
- You have a very long path: `C:/Users/myaseen/Documents/was/libimobiledevice-windows/vcpkg`. Perhaps try installing VCPKG in C:\Users\myaseen\vcpkg
- Are you running this from the Windows command prompt? Because your slashes are inverted (/ instead of \).
